import "./globals.css";
import type { Metadata } from "next";
import { Manrope, Anton, Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable, "scroll-smooth")}>
      <body
        className={`${manrope.variable} ${anton.variable} bg-zinc-950 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
